name: QuizCI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses : actions/checkout@v1

      - name: Send all materials
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          port: "22"
          source: "index.html,index.css,index.js"
          target: "/var/www/html/distQuiz"
